services:
  - type: web
    name: finsight-api
    env: python
    plan: free
    buildCommand: |
      # Recreate local directory structure
      mkdir -p API
      mkdir -p FinSightApp
      # Copy API files to API/
      cp FinSightApp/API/*.py API/
      cp FinSightApp/API/requirements.txt API/
      # Copy ML model files to FinSightApp/
      cp FinSightApp/*.pkl FinSightApp/
      cp FinSightApp/*.keras FinSightApp/
      # Install Python dependencies
      pip install -r API/requirements.txt
    startCommand: uvicorn API.main:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /docs
