services:
  - type: web
    name: finsight-api
    env: python
    plan: free
    buildCommand: >
      cp FinSightApp/API/*.py . &&
      cp FinSightApp/API/requirements.txt . &&
      cp FinSightApp/*.pkl . &&
      cp FinSightApp/*.keras . &&
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /docs
