services:
  - type: web
    name: finsight-api
    env: python
    plan: free
    buildCommand: |
      # Copy API files to root
      cp FinSightApp/API/*.py .
      cp FinSightApp/API/requirements.txt .
      
      # Copy ML model files from FinSightApp directory
      cp FinSightApp/*.pkl . 2>/dev/null || true
      cp FinSightApp/*.keras . 2>/dev/null || true
      
      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /docs
