services:
  - type: web
    name: finsight-api
    env: python
    plan: free
    workingDir: FinSightApp/API
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: python-3.11.4
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /docs
